### ISSUE TITLE
find gov website

### ISSUE THREAD

**Issue by Ztrimus** [Ztrimus/gov-benefit-llama-hack#1]
Types of Government Benefits
Government benefits typically include:
- [ ] Financial assistance programs (e.g., unemployment insurance, welfare)
- [ ] Healthcare benefits (e.g., Medicaid, Medicare)
- [ ] Food assistance (e.g., SNAP, WIC)
- [ ] Housing assistance (e.g., Section 8 vouchers)
- [ ] Education benefits (e.g., student loans, grants)
- [ ] Disability benefits
- [ ] Veterans' benefits

**Comment by sverma89asu** [comment]
https://home.treasury.gov/
https://childcare.gov/
https://studentaid.gov/
https://www.dhs.gov
https://www.hhs.gov
https://22007apply.gov/
https://www.usa.gov
https://studentaid.gov
https://www.grants.gov/
https://www.healthcare.gov
https://www.dol.gov/
https://www.opm.gov/
https://www.cms.gov/
https://www.bls.gov/
https://www.fns.usda.gov/
https://www.nutrition.gov
https://www.hud.gov
https://www.rd.usda.gov
https://www.ssa.gov/
https://www.va.gov/
https://otda.ny.gov/
https://www.benefits.va.gov
https://benefits.va.gov/
https://www.va.gov/
